version: 2.1

executors:
  notebook-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo

jobs:
    Build_JDAT_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: ./.circleci/builder/factory.py -c jdat_notebooks

    Build_HST_NB_VIZ_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: ./.circleci/builder/factory.py -c hst_nb_viz
    Build_Jupyter_Platform_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: ./.circleci/builder/factory.py -c jupyter_platform
    Build_JWST_NB_VIZ_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: ./.circleci/builder/factory.py -c jwst_nb_viz
    Build_Concept_APIS:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: ./.circleci/builder/factory.py -c concept_APIs
  Build_Notebooks:
    executor: notebook-executor
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            ./.circleci/setup_env.sh

      - run:
          name: Build Notebooks
          command: |
            python ./.circleci/builder/factory.py -c jdat_notebooks

            # - run:
            #     name: Build Artifacts
            #     command: |
            #       source activate notebooks_env
            #       python ./.circleci/build_artifacts.py

            # - store_test_results:
            #     path: /tmp/test-results

            # - run:
            #     name: Consolidate Pages
            #     command: |
            #       source activate notebooks_env
            #       python ./.circleci/consolidate_pages.py

      - add_ssh_keys
      # - run:
      #     name: Deploy Pages
      #     command: |
      #       bash ./.circleci/deploy-notebooks.sh


workflows:
  version: 2.1

  build-deploy:
    jobs:
      - Build_Notebooks
